name: Android

on:
  push:
    tags:
      - '*release'

jobs:
  build:
    environment: sunbird
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install specific platform and build tools
      run: |
        echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-35" 
        echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
        echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Check Android SDK versions
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "Available Android platforms:"
        ls -la $ANDROID_SDK_ROOT/platforms/
        echo "Available build tools:"
        ls -la $ANDROID_SDK_ROOT/build-tools/

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x

    - name: Install Ionic
      run: npm install -g @ionic/cli
      
    - name: Clean npm & Cordova cache 
      run: |
        npm cache clean --force
        rm -rf node_modules plugins platforms package-lock.json
        rm -rf ~/.cordova
        npx cordova platform remove android || true

    - name: Install app dependencies
      run: npm install --legacy-peer-deps

    - name: Generate App Assets
      run: npx @capacitor/assets generate --iconBackgroundColor '#ffffff' --iconBackgroundColorDark '#222222' --splashBackgroundColor '#ffffff' --splashBackgroundColorDark '#111111'

    - name: Convert Windows line endings to Linux from the gradlew file
      run: sudo apt update && sudo apt install dos2unix && cd android && dos2unix ./gradlew && cd ..

    - name: Make ./gradlew command executable
      run: cd android && chmod +x ./gradlew && cd ..
    
    - name: Decode google-service
      id: decode_google-service
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'google-services.json'
        fileDir: '/home/runner/work/SunbirdEd-mobile-app/SunbirdEd-mobile-app/configurations/'
        encodedString: ${{ secrets.PROD_GOOGLE_SERVICE_CONTENT }}

    - name: Replace secrets in gradle.properties
      run: |
        sed -i 's|^base_url=.*|base_url=${{ vars.BASE_URL }}|' android/gradle.properties
        sed -i 's|^channel_id=.*|channel_id=${{ vars.CHANNEL_ID }}|' android/gradle.properties
        sed -i 's|^mobile_app_key=.*|mobile_app_key=${{ secrets.PROD_MOBILE_APP_KEY }}|' android/gradle.properties
        sed -i 's|^mobile_app_secret=.*|mobile_app_secret=${{ secrets.PROD_MOBILE_APP_SECRET }}|' android/gradle.properties
    
    - name: Decode Production Keystore
      id: decode_prod_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'android_keystore.jks'
        fileDir: '/home/runner/work/SunbirdEd-mobile-app/SunbirdEd-mobile-app/android/app/keystore/'
        encodedString: ${{ secrets.PROD_KEYSTORE }}
    
    - name: Create signing.properties from JSON secret
      run: |
        mkdir -p ${{ github.workspace }}/android/app/keystore

        trap 'rm -f signing.json' EXIT

        echo "${{ secrets.PROD_SIGNING_KEYS }}" | base64 --decode > signing.json

        PROD_SIGNING_STORE_PASSWORD=$(jq -r '.PROD_SIGNING_STORE_PASSWORD' signing.json)
        PROD_SIGNING_KEY_ALIAS=$(jq -r '.PROD_SIGNING_KEY_ALIAS' signing.json)
        PROD_SIGNING_KEY_PASSWORD=$(jq -r '.PROD_SIGNING_KEY_PASSWORD' signing.json)

        touch ${{ github.workspace }}/android/signing.properties
        echo "PROD_KEYSTORE=${{ github.workspace }}/android/app/keystore/android_keystore.jks" >> ${{ github.workspace }}/android/signing.properties
        echo "PROD_SIGNING_STORE_PASSWORD=$PROD_SIGNING_STORE_PASSWORD" >> ${{ github.workspace }}/android/signing.properties
        echo "PROD_SIGNING_KEY_ALIAS=$PROD_SIGNING_KEY_ALIAS" >> ${{ github.workspace }}/android/signing.properties
        echo "PROD_SIGNING_KEY_PASSWORD=$PROD_SIGNING_KEY_PASSWORD" >> ${{ github.workspace }}/android/signing.properties

    - name: Build Ionic assets
      run: ionic build --prod

    - name: Capacitor Sync
      run: npx cap sync android

    - name: Copy and update android
      run: npx cap copy android && npx cap update android

    - name: Copy content-player files to Android assets
      run: |
        if [ ! -d "www/content-player" ]; then
          echo "Source directory www/content-player does not exist!"
          exit 1
        fi
        mkdir -p android/app/src/main/assets/public/content-player
        cp -r www/content-player/* android/app/src/main/assets/public/content-player/
        ls -R android/app/src/main/assets/public/content-player

    - name: Decode and export signing config
      id: signing
      run: |
        trap 'rm -f prod_signing.json' EXIT

        echo "${{ secrets.PROD_SIGNING_KEYS }}" | base64 --decode > prod_signing.json

        echo "PROD_SIGNING_KEY_ALIAS=$(jq -r '.PROD_SIGNING_KEY_ALIAS' prod_signing.json)" >> $GITHUB_ENV
        echo "PROD_SIGNING_KEY_PASSWORD=$(jq -r '.PROD_SIGNING_KEY_PASSWORD' prod_signing.json)" >> $GITHUB_ENV
        echo "PROD_SIGNING_STORE_PASSWORD=$(jq -r '.PROD_SIGNING_STORE_PASSWORD' prod_signing.json)" >> $GITHUB_ENV

    - name: Cleanup
      if: always()
      run: |
        rm -f prod_signing.json

    - name: Fix missing resources in capacitor-cordova-android-plugins
      run: |
        echo "Copying resources to capacitor-cordova-android-plugins..."
        mkdir -p android/capacitor-cordova-android-plugins/src/main/res
        cp -r android/app/src/main/res/* android/capacitor-cordova-android-plugins/src/main/res/

    - name: Build release AAB
      run: cd android && ./gradlew bundleRelease --stacktrace

    - name: Verify AAB was created
      run: |
        AAB_FILES=$(find android/app/build/outputs/bundle/release/ -name "*.aab" | wc -l)
        if [ "$AAB_FILES" -eq 0 ]; then
          echo "AAB file not found!"
          ls -la android/app/build/outputs/bundle/release/ || echo "Release directory does not exist"
          exit 1
        fi
        echo "AAB files found:"
        find android/app/build/outputs/bundle/release/ -name "*.aab" -exec ls -la {} \;
        echo "AAB file created successfully."

    - name: Upload Release AAB
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: android/app/build/outputs/bundle/release/*.aab

    - name: Set versionName to environment
      run: |
        VERSION_NAME=$(grep '^version_name=' android/gradle.properties | cut -d'=' -f2)
        if [ -z "$VERSION_NAME" ]; then
          echo "::error::version_name not found in android/gradle.properties"
          exit 1
        fi
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "Version: $VERSION_NAME"
        
    - name: Upload AAB to Azure Blob Storage
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          AAB_FILE=$(find android/app/build/outputs/bundle/release/ -name "*.aab" | head -1)
          if [ -z "$AAB_FILE" ]; then
           echo "AAB file not found!"
           exit 1
          fi

          echo "Uploading AAB file: $AAB_FILE"

          az storage blob upload \
            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
            --container-name "${{ vars.AZURE_CONTAINER_NAME }}" \
            --file "$AAB_FILE" \
            --name "sunbird-release-${{ env.VERSION_NAME }}-${{ github.run_number }}.aab" \
            --overwrite

          echo "AAB file successfully uploaded to Azure Blob Storage: sunbird-release-${{ env.VERSION_NAME }}-${{ github.run_number }}.aab"